apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: sample
spec:
  collectors:
    - mssql:
        collectorName: mssql
        uri: sqlserver://SA:P%40w0rd1@technonook.com:1433/master
  analyzers:
    - mssql:
        checkName: Must be SQLServer 15.x or later
        collectorName: mssql
        outcomes:
          - fail:
              when: "connected == false"
              message: Cannot connect to SQLServer
          - fail:
              when: "version < 15.x"
              message: The SQLServer must be at least version 15
          - pass:
              message: The SQLServer connection checks out
